### ISSUE TITLE
Calling done(new Error(""), {}) will crash the server without reply.

### ISSUE THREAD

**Issue by sorin7486** [rjrodger/seneca-web#2]
The following line will crash the server:

    done(new Error('this is a test'), {});

I would expect this to send a HTTP 500 response. 

If I call seneca.fail("", done), it doesn't send a reply at all. So it is unclear to me how to treat errors, apart from sending an {error: true} response. I managed to find a solution by looking at the REST module code, though this doesn't seem to be documented:

    done(null, {httpstatus$: 500});

**Comment by rjrodger** [comment]
documented and fixed as of 0.4.0
