### ISSUE TITLE
`alias` does not seem to work

### ISSUE THREAD

**Issue by faceleg** [rjrodger/seneca-web#21]
> alias: custom URL path, concatenated to top level prefix; can contain Express-style route parameters: /api/:bar sets req.params.bar.

My express integration is elsewhere - it works fine.

I'm trying to make the `put` seneca function available at `/api/users/:id`, but haven't been able to do so with the `alias` property.

I've been able to make it work by renaming it from `put` to `:id`, but I'd much rather use `alias` and keep the name as `put`. I'm going to have other verbs i.e. `get`, `delete`, I'd rather differentiate them at the map level than have a bunch of conditionals inside one `:id` function.

Am I doing it wrong?

```JS
'use strict';

module.exports = function userPlugin(options) {

  var seneca = this;
  var pluginName = 'users';

  options = seneca.util.deepextend({
    prefix: '/api/users'
  });

  seneca.add({
    init: pluginName
  }, init);

  seneca.add({
    role: pluginName,
    cmd: 'put'
  }, put);

  seneca.act({
    role: 'web',
    use: {
      prefix: options.prefix,
      pin: {
        role: pluginName,
        cmd: '*'
      },
      map: {
        put: {
          PUT: true,
          alias: '/api/users/:id'
        }
      }
    }
  });

  return {
    name: pluginName
  };

  function init(args, done) {
    done();
  }

  function put(args, done) {
    console.log(args);
    done();
  }
};
```

**Comment by faceleg** [comment]
> alias: custom URL path, concatenated to top level prefix; can contain Express-style route parameters: /api/:bar sets req.params.bar.

My express integration is elsewhere - it works fine.

I'm trying to make the `put` seneca function available at `/api/users/:id`, but haven't been able to do so with the `alias` property.

Am I doing it wrong?

```JS
'use strict';

module.exports = function userPlugin(options) {

  var seneca = this;
  var pluginName = 'users';

  options = seneca.util.deepextend({
    prefix: '/api/users'
  });

  seneca.add({
    init: pluginName
  }, init);

  seneca.add({
    role: pluginName,
    cmd: 'put'
  }, put);

  seneca.act({
    role: 'web',
    use: {
      prefix: options.prefix,
      pin: {
        role: pluginName,
        cmd: '*'
      },
      map: {
        put: {
          PUT: true,
          alias: '/api/users/:id'
        }
      }
    }
  });

  return {
    name: pluginName
  };

  function init(args, done) {
    done();
  }

  function put(args, done) {
    console.log(args);
    done();
  }
};
```

**Comment by faceleg** [comment]
I will submit a PR if I can prove this doesn't work by adding a relevant test to this module.

**Comment by mcdonnelldean** [comment]
@faceleg Could you add the test please? There are some new people ramping up to the org so this will speed up the process and we should be able to get this sorted :D

**Comment by faceleg** [comment]
I'll deal with #22 first, as ... well I have to.

**Comment by rjrodger** [comment]
@faceleg your code does look like it should work :(
Try running you app and calling role:web,list:route to see the list of URL routes defined.
Easiest way to do this is to call `seneca_instance.repl()` and telnet localhost 30303, and then enter `role:web,list:route` - post the output here

**Comment by faceleg** [comment]
Thanks @rjrodger, will do.

**Comment by faceleg** [comment]
@rjrodger see #23, alias works only if one omits the prefix from the alias - I was doing it wrong.

Once the tests are merged in, other n00bs like me will have a slightly more complete reference :)
