### ISSUE TITLE
Supertest to test express integration

### ISSUE THREAD

**Issue by faceleg** [rjrodger/seneca-web#22]
Is anyone against using this instead of the bash script in use currently?

If not, expect a PR.

In fact expect one anyway, no way I want to contribute unit tests if I have to copy-paste bash

**Comment by mcdonnelldean** [comment]
@faceleg I'm happy to look over it and at at the least get a discussion going. Anything that improves test experience interests me.

**Comment by faceleg** [comment]
You will love it, trust me.

**Comment by rjrodger** [comment]
@faceleg supertest?

**Comment by faceleg** [comment]
https://github.com/visionmedia/supertest

**Comment by faceleg** [comment]
Uh, I also added an eslintrc and jscsrc file, and a gulp task that will reject commits that do not conform.

Thinking about it, eslint has progressed to the point where I think it covers all of the jscs features I liked (formatting mainly), so I'll push a commit removing it just now.

Note also that I guessed at your preferred code style based on what I have seen in seneca-land so far.

**Comment by faceleg** [comment]
Closing, please discuss on #23

**Comment by rjrodger** [comment]
supertest: nice! /cc @mcdonnelldean
